name: Full CD Pipeline

on:
  push:
    branches: ["main"]


jobs:
  debug-token:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get OIDC Token
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
            | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d "." -f2)

          echo "$PAYLOAD" | base64 -d

      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 3. Configure AWS credentials (simple version)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050922969172:role/github-action
          aws-region: eu-west-1

      # 6. Terraform deploy
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 3. Build JAR (CI inside CD)
      - name: Build JAR
        run: mvn clean package
        working-directory: ../lambda-app

      # 5. Upload artifact to S3
      - name: Upload JAR
        run: |
          aws s3 cp ../lambdaapp/target/*.jar \
          s3://harneet-artifact-bucket/lambdaapp/firstlambda.jar