name: Full CD Pipeline

on:
  push:
    branches: ["main"]


jobs:
  debug-token:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      # 1. Checkout code
      - uses: actions/checkout@v3

      - name: Set artifact name
        run: echo "ARTIFACT_NAME=lambdaapp-1.0.1.jar" >> $GITHUB_ENV

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 3. Configure AWS credentials (simple version)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050922969172:role/github-action
          aws-region: eu-west-1

      #Deploy Lamda
      - name: Deploy updated JAR to lambda
        run: |
          aws lambda update-function-code \
              --function-name file-processor \
              --s3-bucket harneet-artifact-bucket \
              --s3-key lambdaapp/${ARTIFACT_NAME}
      

      # 6. Terraform deploy
     # - name: Terraform Init
     #   run: terraform init

     # - name: Terraform Apply
      #  run: |
       #   terraform apply \
      #      -auto-approve \
      #      -var="lambda_artifact=lambdaapp/${ARTIFACT_NAME}"
